
foo: 1
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:1125/eureka/
rabbitmq:
  host: localhost
  port: 5672
  username: guest
  password: guest

spring:
  profiles:
    active: dev